spring:
  application:
    name: market_be

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/marketdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 1000MB       # 단일 파일 최대 크기
      max-request-size: 1000MB    # 전체 요청 최대 크기
